language: generic
dist: xenial
git:
  depth: 10

jobs:
  include:
    - name: Vim 7.4
      env:
      - VIM_VERSION=v7.4
      - MAKE_TARGET=test
      - TEST_PROFILE=vim-profile-v7.4.txt
    - name: Vim v8
      env:
      - VIM_VERSION=v8.0.0000
      - MAKE_TARGET=test
      - TEST_PROFILE=vim-profile-v8.0.txt
    - name: Vim master
      env:
      - VIM_VERSION=master
      - MAKE_TARGET=test
      - TEST_PROFILE=vim-profile-master.txt
    - name: Installed Vim with checks
      env:
      - VIM_VERSION=installed
      - MAKE_TARGET="clean_compiled check checkpy js/test py/test test/node_position/test_position.out"
      - TEST_PROFILE=vim-profile-installed.txt

install:
  - |
    if [ "$VIM_VERSION" = 'installed' ]; then
      pip install --user flake8
    else
      bash scripts/install-vim.sh
      export PATH=$HOME/vim/bin:$PATH
    fi
  - pip install covimerage --user

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - make --keep-going $MAKE_TARGET

after_success:
  - covimerage write_coverage $TEST_PROFILE
  - coverage xml
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
