language: generic
sudo: false
git:
  depth: 10

matrix:
  include:
    - env:
      - VIM_VERSION=v7.4
      - MAKE_TARGET=test
    - env:
      - VIM_VERSION=v8.0.0000
      - MAKE_TARGET=test
    - env:
      - VIM_VERSION=master
      - MAKE_TARGET=test
    - env:
      - VIM_VERSION=installed
      - MAKE_TARGET="clean_compiled check js/test py/test vim/test"

install:
  - |
    if [ "$VIM_VERSION" != 'installed' ]; then
      bash scripts/install-vim.sh
      export PATH=$HOME/vim/bin:$PATH
    fi

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - make $MAKE_TARGET
